version: '3'
services:
  api:
    container_name: debug_test_api
    environment:
      - DB_NAME=habits
      - DB_CONNECTION=mongodb://AATTWM:habitspass@db:27017
      - NODE_ENV=test
    depends_on:
      - db
    tty: true

  db:
    container_name: debug_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_DATABASE=habits_test
volumes:
  test_db:
networks:
  default:
    name: debug_test