version: '3'
services:
  api:
    container_name: habit_tracker_dev_api
    ports:
      - 3000:3000
    environment:
      - DB_NAME=habits
      - DB_CONNECTION=mongodb://AATTWM:habitspass@db:27017
    depends_on:
      - db
    command: bash -c "npm install && npm run dev"

  db:
    container_name: habit_tracker_dev_db
    volumes:
      - "dbdata:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_DATABASE=habits
volumes:
  dbdata:
networks:
  default:
    name: habit_tracker_api