version: '3'
services:
  server:
    container_name: debug_test_server
    ports:
      - 3000:3000
    environment:
      - DB_NAME=habits
      - DB_CONNECTION=mongodb://AATTWM:habitspass@db:27017
      - NODE_ENV=test
    depends_on:
      - db
    tty: true
    command: bash -c "npm install && npm test"

  db:
    container_name: debug_test_db
    volumes:
      - "test_db:/var/lib/mongodb/data"
    environment:
      - MONGO_INITDB_DATABASE=habits_test
volumes:
  test_db:
networks:
  default:
    name: debug_test